### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xae in position 9: invalid start byte

### ISSUE THREAD

**Issue by hasegaw** [hasegaw/IkaLog#198]
```
WinIkaLog_ja.BATを実行すると以下のメッセージが出力されます。
Ikalogのウインドウ自体は起動しますが、応答なし状態から変化しません。
なお、この挙動は最新版と安定版でも変わりはありません。
------------------------------------------------------------
【WinIkaLog_ja.BAT実行結果】

IkaLog Primary CLI Language: ja_JP (set LANG to override)
IkaLog Game Language: ja (set IKALOG_LANG to override)
<ikalog.utils.icon_recoginizer.weapon.WeaponRecoginizer object at 0x05607770>: KNN Trained (6967 samples)
イカ、よろしく～

***** VIDEOINPUT LIBRARY - 0.2000 - TFW2013 *****



IkaUI got an exception and crashed >>>>
Traceback (most recent call last):
  File "IkaUI.py", line 111, in <module>
  File "IkaUI.py", line 47, in IkaUI_main
  File "Z:\hasegaw\work\IkaLogPY2EXE\ikalog\ui\capture.py", line 239, in on_option_tab_create
  File "Z:\hasegaw\work\IkaLogPY2EXE\ikalog\ui\capture.py", line 63, in enumerate_devices
  File "Z:\hasegaw\work\IkaLogPY2EXE\ikalog\inputs\win\videoinput_wrapper.py", line 105, in get_device_list
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xae in position 9: invalid start byte

<<<<

------------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------------

【utf-8 対応確認コマンド結果】


Microsoft Windows [Version 10.0.10586]
(c) 2015 Microsoft Corporation. All rights reserved.

C:\Users\admin>python
Python 3.5.1 (v3.5.1:37a07cee5969, Dec  6 2015, 01:38:48) [MSC v.1900 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> sys.getdefaultencoding()
'utf-8'
>>>

```

**Comment by hasegaw** [comment]
もしかして video_input.dll からデバイス名が Unicode なの受け取ったりすると死ぬ？

**Comment by hasegaw** [comment]
https://github.com/hasegaw/IkaLog/blob/de1887ca19c07bbc1af32dfa24e39404bfb5ef48/ikalog/inputs/win/videoinput_wrapper.py#L105

まさかここで非ASCIIな文字がくるとか

**Comment by hasegaw** [comment]
たぶん直ったはず

**Comment by hasegaw** [comment]
![unnamed](https://cloud.githubusercontent.com/assets/2528004/14934556/7eb13c22-0eee-11e6-8daf-3b8a6d8c2d71.png)

**Comment by hasegaw** [comment]
```
公開していただいた新しいバージョンで、問題なく起動・動作しました！
原因が分からず途方に暮れていたところでしたが、念願叶いました。
素早い対応をしていただき、本当にありがとうございました。
```
