### ISSUE TITLE
outputs/statink: Undefined reference

### ISSUE THREAD

**Issue by hasegaw** [hasegaw/IkaLog#205]
```
IkaLogの動作する時のログに、こんな感じのメッセージが出ます。 Traceback (most recent call last): File "C:\IkaLog.py\Python34\lib\threading.py", line 911, in _bootstrap_inner self.run() File "C:\IkaLog.py\Python34\lib\threading.py", line 859, in run self._target(*self._args, **self._kwargs) File "C:\IkaLog.py\IkaLog\ikalog\outputs\statink.py", line 617, in _post_payload_worker if error: NameError: name 'error' is not defined ソースを見てみたのですが、他の関数では 事前にerror = false みたいに定義しているのですが、statink.py"の line 617では、いきなり if error:となっていて、これが原因のような気がします。 
```

**Comment by hasegaw** [comment]
No applicable code path in 636bd677dabf8c25959f78cb6b4d434187d263dc AFAIK
