### ISSUE TITLE
ui/videocapture: object has no attribute 'get_epoch_time'

### ISSUE THREAD

**Issue by hasegaw** [hasegaw/IkaLog#305]
IkaUI only

IkaUI uses special input class VideoCapture that left behind ikalog.inputs interface change.

```
IkaUI got an exception and crashed >>>>
Traceback (most recent call last):
  File "IkaUI.py", line 111, in <module>
  File "IkaUI.py", line 52, in IkaUI_main
  File "C:\IkaLogCI\IkaLogPY2EXE\ikalog\engine.py", line 366, in set_capture
  File "C:\IkaLogCI\IkaLogPY2EXE\ikalog\engine.py", line 370, in reset_capture
AttributeError: 'VideoCapture' object has no attribute 'get_epoch_time'

<<<<
```

**Comment by hiroyuki-komatsu** [comment]
https://github.com/hasegaw/IkaLog/pull/306 will fix it.

**Comment by hasegaw** [comment]
Confirmed the fix
