### ISSUE TITLE
GameKillで例外が発生する

### ISSUE THREAD

**Issue by wkoichi** [hasegaw/IkaLog#322]
最新のmasterでmp4を入力として実行したときに例外が発生しました。この例外が発生するとstat.inkへPOSTするJSONを作成するときにも例外が発生するようです。

例外が発生する部分の抜粋
https://www.dropbox.com/s/qm74uv6c0sbnhad/2016-06-11.mp4?dl=0

```
GameKill raised a exception >>>>
Traceback (most recent call last):
  File "/Users/***/IkaLog.statink/ikalog/engine.py", line 263, in process_scene
    scene.match(context)
  File "/Users/***/IkaLog.statink/ikalog/scenes/scene.py", line 110, in match
    self._matched = self.match_no_cache(context)
  File "/Users/***/IkaLog.statink/ikalog/scenes/game/kill.py", line 123, in match_no_cache
    current_kills = self.find_kill_messages(context)
  File "/Users/***/IkaLog.statink/ikalog/scenes/game/kill.py", line 80, in find_kill_messages
    img_name_norm = normalize_player_name(img_name[:, img_name_left :img_name_right])
  File "/Users/***/IkaLog.statink/ikalog/utils/player_name.py", line 31, in normalize_player_name
    img_name_w = matcher.MM_WHITE(sat=(0, 96), visibility=(48, 255))(img_name)
  File "/Users/***/IkaLog.statink/ikalog/utils/image_filters/filters.py", line 45, in __call__
    return self._run_filter(img_bgr=img_bgr, img_gray=img_gray)
  File "/Users/***/IkaLog.statink/ikalog/utils/image_filters/filters.py", line 79, in _run_filter
    img_match_s = cv2.inRange(img_hsv[:, :, 1], sat_min, sat_max)
TypeError: 'NoneType' object is not subscriptable

<<<<<

StatInk.on_game_session_end() raised a exception >>>>
Traceback (most recent call last):
  File "/Users/***/IkaLog.statink/ikalog/engine.py", line 103, in call_plugin
    getattr(plugin, event_name)(context)
  File "/Users/***/IkaLog.statink/ikalog/outputs/statink.py", line 756, in on_game_session_end
    self._close_game_session(context)
  File "/Users/***/IkaLog.statink/ikalog/outputs/statink.py", line 740, in _close_game_session
    payload = self.composite_payload(context)
  File "/Users/***/IkaLog.statink/ikalog/outputs/statink.py", line 386, in composite_payload
    payload['agent_custom'] = self.composite_agent_custom(context)
  File "/Users/***/IkaLog.statink/ikalog/outputs/statink.py", line 274, in composite_agent_custom
    return json.dumps(custom, separators=(',', ':'))
NameError: name 'json' is not defined

<<<<<
```

**Comment by hasegaw** [comment]
```
GitHub の master だと、動画データによっては例外が発生しますね。

[11:53]
Yesterday at 11:53 PM
Open in archives
 Star this message
<ikalog.scenes.result_detail.ResultDetail object at 0x116519470>: switching to state _state_tracking
ResultDetail raised a exception >>>>
Traceback (most recent call last):
 File "/Users/komatsu/github/IkaLog/ikalog/engine.py", line 263, in process_scene
   scene.match(context)
 File "/Users/komatsu/github/IkaLog/ikalog/scenes/scene.py", line 110, in match
   self._matched = self.match_no_cache(context)
 File "/Users/komatsu/github/IkaLog/ikalog/scenes/stateful_scene.py", line 36, in match_no_cache
   return self._state(context)
 File "/Users/komatsu/github/IkaLog/ikalog/scenes/result_detail.py", line 818, in _state_tracking
   self.analyze(context)
 File "/Users/komatsu/github/IkaLog/ikalog/scenes/result_detail.py", line 685, in analyze
   e = self.analyze_entry(img_entry)
 File "/Users/komatsu/github/IkaLog/ikalog/scenes/result_detail.py", line 616, in analyze_entry
   "img_name_normalized": normalize_player_name(img_name),
 File "/Users/komatsu/github/IkaLog/ikalog/utils/player_name.py", line 43, in normalize_player_name
   img_name_left = np.min(img_name_x_hist)
 File "/usr/local/lib/python3.5/site-packages/numpy/core/fromnumeric.py", line 2350, in amin
   out=out, keepdims=keepdims)
 File "/usr/local/lib/python3.5/site-packages/numpy/core/_methods.py", line 29, in _amin
   return umr_minimum(a, axis, None, out, keepdims)
ValueError: zero-size array to reduction operation minimum which has no identity

<<<<<
```

**Comment by wkoichi** [comment]
commitされていたので、feature/on_game_killed_nameブランチの最新で処理してみたところ、違う例外が発生しました。

```
GameKill raised a exception >>>>
Traceback (most recent call last):
  File "/Users/wkoichi/IkaLog.statink/ikalog/engine.py", line 263, in process_scene
    scene.match(context)
  File "/Users/wkoichi/IkaLog.statink/ikalog/scenes/scene.py", line 110, in match
    self._matched = self.match_no_cache(context)
  File "/Users/wkoichi/IkaLog.statink/ikalog/scenes/game/kill.py", line 123, in match_no_cache
    current_kills = self.find_kill_messages(context)
  File "/Users/wkoichi/IkaLog.statink/ikalog/scenes/game/kill.py", line 80, in find_kill_messages
    img_name_norm = normalize_player_name(img_name[:, img_name_left :img_name_right])
  File "/Users/wkoichi/IkaLog.statink/ikalog/utils/player_name.py", line 54, in normalize_player_name
    if not (img_left < img_right):
NameError: name 'img_left' is not defined

<<<<<
```

ここの変数名が`img_name_left`と`img_name_right`ですかね？
```python
    if not (img_left < img_right):
        return None
```

手元で直して処理してみましたが、元々の例外`TypeError: 'NoneType' object is not subscriptable`はまだ発生しました。

**Comment by hasegaw** [comment]
さきほど master にマージしたものでそのへん修正したつもりです。よろしければ再現するか試していただけないでしょうか。

**Comment by wkoichi** [comment]
最新のmasterで処理したところ、問題ありませんでした。
ありがとうございます。

**Comment by hasegaw** [comment]
入力内容に依存する問題もありテストいただけてこちらも助かりました。
