### ISSUE TITLE
NameError: name 'PerCharacter' is not defined

### ISSUE THREAD

**Issue by hasegaw** [hasegaw/IkaLog#38]
master のコードにて、 PerCharacter クラスが見えていないようです。
__init__.py には定義されていますが。。。？？
IkaLog は止まってはいませんが文字認識機能が全滅中。

````
Exception occured in Udemae recoginization.
Traceback (most recent call last):
  File "/Users/hasegaw/work/IkaLog_github/ikalog/scenes/result_detail.py", line 280, in analyze_entry
    'img_score']).upper()
  File "/Users/hasegaw/work/IkaLog_github/ikalog/utils/character_recoginizer/character.py", line 164, in match
    samples = self.find_samples(img)
  File "/Users/hasegaw/work/IkaLog_github/ikalog/utils/character_recoginizer/character.py", line 127, in find_samples
    characters = self.extract_characters(img)
  File "/Users/hasegaw/work/IkaLog_github/ikalog/utils/character_recoginizer/character.py", line 109, in extract_characters
    x_cutter = PerCharacter()
NameError: name 'PerCharacter' is not defined
````

**Comment by hasegaw** [comment]
再現方法

````
Takeshis-MacBook-Pro:IkaLog_github hasegaw$ python3 test/ResultDetail.py screenshots/ikabattle_20150825_2112.png
start model.train 876
done model.train
Loaded weapons recoginization model.
Loaded number recoginization model.
Loaded udemae recoginization model.
Exception occured in K/D recoginization.
Traceback (most recent call last):
  File "/Users/hasegaw/work/IkaLog_github/ikalog/scenes/result_detail.py", line 288, in analyze_entry
    'img_rank'])
  File "/Users/hasegaw/work/IkaLog_github/ikalog/utils/character_recoginizer/character.py", line 174, in match_digits
    return int(self.match(img))
  File "/Users/hasegaw/work/IkaLog_github/ikalog/utils/character_recoginizer/character.py", line 164, in match
    samples = self.find_samples(img)
  File "/Users/hasegaw/work/IkaLog_github/ikalog/utils/character_recoginizer/character.py", line 127, in find_samples
    characters = self.extract_characters(img)
  File "/Users/hasegaw/work/IkaLog_github/ikalog/utils/character_recoginizer/character.py", line 109, in extract_characters
    x_cutter = PerCharacter()
NameError: name 'PerCharacter' is not defined

Exception occured in K/D recoginization.
Traceback (most recent call last):
  File "/Users/hasegaw/work/IkaLog_github/ikalog/scenes/result_detail.py", line 288, in analyze_entry
    'img_rank'])
  File "/Users/hasegaw/work/IkaLog_github/ikalog/utils/character_recoginizer/character.py", line 174, in match_digits
    return int(self.match(img))
  File "/Users/hasegaw/work/IkaLog_github/ikalog/utils/character_recoginizer/character.py", line 164, in match
    samples = self.find_samples(img)
  File "/Users/hasegaw/work/IkaLog_github/ikalog/utils/character_recoginizer/character.py", line 127, in find_samples
    characters = self.extract_characters(img)
  File "/Users/hasegaw/work/IkaLog_github/ikalog/utils/character_recoginizer/character.py", line 109, in extract_characters
    x_cutter = PerCharacter()
NameError: name 'PerCharacter' is not defined

Exception occured in K/D recoginization.
Traceback (most recent call last):
  File "/Users/hasegaw/work/IkaLog_github/ikalog/scenes/result_detail.py", line 288, in analyze_entry
    'img_rank'])
  File "/Users/hasegaw/work/IkaLog_github/ikalog/utils/character_recoginizer/character.py", line 174, in match_digits
    return int(self.match(img))
  File "/Users/hasegaw/work/IkaLog_github/ikalog/utils/character_recoginizer/character.py", line 164, in match
    samples = self.find_samples(img)
  File "/Users/hasegaw/work/IkaLog_github/ikalog/utils/character_recoginizer/character.py", line 127, in find_samples
    characters = self.extract_characters(img)
  File "/Users/hasegaw/work/IkaLog_github/ikalog/utils/character_recoginizer/character.py", line 109, in extract_characters
    x_cutter = PerCharacter()
NameError: name 'PerCharacter' is not defined

Exception occured in K/D recoginization.
Traceback (most recent call last):
  File "/Users/hasegaw/work/IkaLog_github/ikalog/scenes/result_detail.py", line 288, in analyze_entry
    'img_rank'])
  File "/Users/hasegaw/work/IkaLog_github/ikalog/utils/character_recoginizer/character.py", line 174, in match_digits
    return int(self.match(img))
  File "/Users/hasegaw/work/IkaLog_github/ikalog/utils/character_recoginizer/character.py", line 164, in match
    samples = self.find_samples(img)
  File "/Users/hasegaw/work/IkaLog_github/ikalog/utils/character_recoginizer/character.py", line 127, in find_samples
    characters = self.extract_characters(img)
  File "/Users/hasegaw/work/IkaLog_github/ikalog/utils/character_recoginizer/character.py", line 109, in extract_characters
    x_cutter = PerCharacter()
NameError: name 'PerCharacter' is not defined

Exception occured in K/D recoginization.
Traceback (most recent call last):
  File "/Users/hasegaw/work/IkaLog_github/ikalog/scenes/result_detail.py", line 288, in analyze_entry
    'img_rank'])
  File "/Users/hasegaw/work/IkaLog_github/ikalog/utils/character_recoginizer/character.py", line 174, in match_digits
    return int(self.match(img))
  File "/Users/hasegaw/work/IkaLog_github/ikalog/utils/character_recoginizer/character.py", line 164, in match
    samples = self.find_samples(img)
  File "/Users/hasegaw/work/IkaLog_github/ikalog/utils/character_recoginizer/character.py", line 127, in find_samples
    characters = self.extract_characters(img)
  File "/Users/hasegaw/work/IkaLog_github/ikalog/utils/character_recoginizer/character.py", line 109, in extract_characters
    x_cutter = PerCharacter()
NameError: name 'PerCharacter' is not defined

Exception occured in K/D recoginization.
Traceback (most recent call last):
  File "/Users/hasegaw/work/IkaLog_github/ikalog/scenes/result_detail.py", line 288, in analyze_entry
    'img_rank'])
  File "/Users/hasegaw/work/IkaLog_github/ikalog/utils/character_recoginizer/character.py", line 174, in match_digits
    return int(self.match(img))
  File "/Users/hasegaw/work/IkaLog_github/ikalog/utils/character_recoginizer/character.py", line 164, in match
    samples = self.find_samples(img)
  File "/Users/hasegaw/work/IkaLog_github/ikalog/utils/character_recoginizer/character.py", line 127, in find_samples
    characters = self.extract_characters(img)
  File "/Users/hasegaw/work/IkaLog_github/ikalog/utils/character_recoginizer/character.py", line 109, in extract_characters
    x_cutter = PerCharacter()
NameError: name 'PerCharacter' is not defined

Exception occured in K/D recoginization.
Traceback (most recent call last):
  File "/Users/hasegaw/work/IkaLog_github/ikalog/scenes/result_detail.py", line 288, in analyze_entry
    'img_rank'])
  File "/Users/hasegaw/work/IkaLog_github/ikalog/utils/character_recoginizer/character.py", line 174, in match_digits
    return int(self.match(img))
  File "/Users/hasegaw/work/IkaLog_github/ikalog/utils/character_recoginizer/character.py", line 164, in match
    samples = self.find_samples(img)
  File "/Users/hasegaw/work/IkaLog_github/ikalog/utils/character_recoginizer/character.py", line 127, in find_samples
    characters = self.extract_characters(img)
  File "/Users/hasegaw/work/IkaLog_github/ikalog/utils/character_recoginizer/character.py", line 109, in extract_characters
    x_cutter = PerCharacter()
NameError: name 'PerCharacter' is not defined

Exception occured in K/D recoginization.
Traceback (most recent call last):
  File "/Users/hasegaw/work/IkaLog_github/ikalog/scenes/result_detail.py", line 288, in analyze_entry
    'img_rank'])
  File "/Users/hasegaw/work/IkaLog_github/ikalog/utils/character_recoginizer/character.py", line 174, in match_digits
    return int(self.match(img))
  File "/Users/hasegaw/work/IkaLog_github/ikalog/utils/character_recoginizer/character.py", line 164, in match
    samples = self.find_samples(img)
  File "/Users/hasegaw/work/IkaLog_github/ikalog/utils/character_recoginizer/character.py", line 127, in find_samples
    characters = self.extract_characters(img)
  File "/Users/hasegaw/work/IkaLog_github/ikalog/utils/character_recoginizer/character.py", line 109, in extract_characters
    x_cutter = PerCharacter()
NameError: name 'PerCharacter' is not defined

{'players': [{'weapon': 'わかばシューター'},
             {'weapon': 'デュアルスイーパーカスタム'},
             {'weapon': 'ロングブラスター'},
             {'weapon': 'N-ZAP89'},
             {'weapon': 'スプラシューターコラボ'},
             {'weapon': 'N-ZAP89'},
             {'weapon': 'カーボンローラー'},
             {'weapon': 'スプラローラーコラボ'}],
 'won': True}
Takeshis-MacBook-Pro:IkaLog_github hasegaw$
````

**Comment by hasegaw** [comment]
__init__.py ではクラス定義してはいけないようなので、
やるなら __init__.py から他の .py ファイルに分割する。
