### ISSUE TITLE
WinIkaLog QA

### ISSUE THREAD

**Issue by hasegaw** [hasegaw/IkaLog#428]
* 初回設定時にデフォルト設定がロードされていない
* プレビュー画面を迂闊に触るとリアルタイム処理が止まって気を使う
* アマレコ16x10警告は各所で誤動作が多いようなので外す

とりあえず思いついた分だけ

**Comment by hasegaw** [comment]
ResultDetailの途中で死ぬ
```
<ikalog.scenes.result_detail.ResultDetail object at 0x08BF8BF0>: weapons recogin
ition started.
Intel MKL FATAL ERROR: Cannot load mkl_intel_thread.dll.
```

**Comment by hasegaw** [comment]
http://stackoverflow.com/questions/34985134/py2exe-mkl-fatal-error-cannot-load-mkl-intel-thread-dll
```
Never mind! I managed to solve it, by copying the required dll from inside numpy/core, into the dist folder that py2exe creates, not outside of it.
```

**Comment by hasegaw** [comment]
Minimum requirements:
```
-rwxr-xr-x 1 hasegaw 197121 15389336 11月 18 02:57 mkl_p4.dll*
-rwxr-xr-x 1 hasegaw 197121  1079496 11月 18 02:56 libiomp5md.dll*
-rwxr-xr-x 1 hasegaw 197121 14206616 11月 18 02:54 mkl_core.dll*
-rwxr-xr-x 1 hasegaw 197121  7679128 11月 18 02:50 mkl_intel_thread.dll*
```

**Comment by hasegaw** [comment]
```
C:\Users\hasegaw\Desktop\WinIkaLog20161118_030859_ec87887\WinIkaLog20161118_030859_ec87887\IkaUI.exe\ikalog\ui\panel\last_result.py:63: wxPyDeprecationWarning: Call to deprecated item BitmapFromBuffer. Use :meth:`Bitmap.FromBuffer` or :meth:`Bitmap.FromBufferAndAlpha` instead.
ResultsGUI.on_game_individual_result() raised a exception >>>>
Traceback (most recent call last):
  File "C:\IkaLogCI\IkaLogPY2EXE\ikalog\ui\panel\last_result.py", line 61, in on_game_individual_result
    self.result_image = wx.Bitmap.FromBuffer(frame_rgb)
TypeError: Bitmap.FromBuffer(): argument 1 has unexpected type 'numpy.ndarray'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\IkaLogCI\IkaLogPY2EXE\ikalog\engine.py", line 103, in call_plugin
    getattr(plugin, event_name)(context)
  File "C:\IkaLogCI\IkaLogPY2EXE\ikalog\ui\panel\last_result.py", line 63, in on_game_individual_result
    self.result_image = wx.BitmapFromBuffer(frame_rgb)
  File "C:\bin\python34\lib\site-packages\wx\core.py", line 79, in deprecated_func
    return item(*args)
TypeError: BitmapFromBuffer() missing 2 required positional arguments: 'height' and 'dataBuffer'

<<<<<
```

**Comment by hasegaw** [comment]
BitmapFromBuffer() はたぶん開発者が利用している wxPython のマイナーバージョンによって挙動が違う系
ビルド環境ではいまこうなってる
```
$ /c/bin/python34/Scripts/pip3.exe  list
backports-abc (0.4)
certifi (2016.2.28)
colorama (0.3.7)
fluent-logger (0.4.0)
msgpack-python (0.4.7)
numpy (1.11.0)
oauthlib (1.0.3)
opencv-python (3.1.0)
Pillow (3.2.0)
pip (8.1.1)
py (1.4.31)
py2exe (0.9.2.2)
pytest (2.9.1)
PyYAML (3.11)
requests (2.9.1)
requests-oauthlib (0.6.1)
setuptools (18.2)
slackweb (1.0.5)
tornado (4.3)
u-msgpack-python (2.1)
urllib3 (1.15)
wxPython-Phoenix (3.0.3.dev1964+f780b21)
You are using pip version 8.1.1, however version 9.0.1 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.
```

**Comment by hasegaw** [comment]
```
Screenshot.on_result_detail_still() raised a exception >>>>
Traceback (most recent call last):
  File "C:\IkaLogCI\IkaLogPY2EXE\ikalog\utils\ikautils.py", line 214, in writeScreenshot
    img_pil.save(destfile)
  File "C:\bin\python34\lib\site-packages\PIL\Image.py", line 1684, in save
    fp = builtins.open(filename, "wb")
FileNotFoundError: [Errno 2] No such file or directory: 'hoge\\ikabattle_20150912_055405.png'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\IkaLogCI\IkaLogPY2EXE\ikalog\engine.py", line 103, in call_plugin
    getattr(plugin, event_name)(context)
  File "C:\IkaLogCI\IkaLogPY2EXE\ikalog\outputs\screenshot.py", line 139, in on_result_detail_still
    IkaUtils.writeScreenshot(destfile, context['engine']['frame'])
  File "C:\IkaLogCI\IkaLogPY2EXE\ikalog\utils\ikautils.py", line 217, in writeScreenshot
    self.dprint("Screenshot: failed")
NameError: name 'self' is not defined

<<<<<
```
最初期に書いたコードのクオリティがアレ

**Comment by hasegaw** [comment]
戦績画面でハング
engine スレッドからのコールバックで wxPython のオブジェクトを触っているけども、 wxPython のオブジェクトはメインスレッドからしか触れないためか。 Bitmap 更新する前後で mutex 取ったり draw_image() がメインスレッドから実行されるように修正が必要

**Comment by hasegaw** [comment]
WUI版が現実的になってきているので次回リリース以降は IkaUI ではなく Web UI ベースで
