### ISSUE TITLE
stat.inkにデータが送信されていない？

### ISSUE THREAD

**Issue by vvakame** [hasegaw/IkaLog#75]
913fd5d86f6908ea395c29b97516391c580c34bd です。
git pull する前までっぽい時は動作していたようです(git pullする前のリビジョンが何かはわからなくなってしまいました…

https://stat.ink/u/vvakame
プライベートマッチを2時間くらいとガチバトルを1時間くらいプレイしてましたがstat.inkにデータが溜まってませんでした。

1戦行った文のログをイカに貼ります。
見た感じ、`(PNG Data)` などが含まれていないので少なくとも StatInk.print_payload が呼ばれてなさそうです。
stateの切り替え機能が入ったっぽいですがstateの切替前に呼んでないとかそういう系ですかね…？

```
[event] 13:43 on_lobby_matched  Lobby_type: public
[event] 13:43 on_lobby_matching  Lobby_type: public
<ikalog.scenes.game.start.GameStart object at 0x10c7b67b8>: switching to state _state_tracking
[(845958, <ikalog.utils.matcher.IkaMatcher object at 0x10c7b68d0>), (846028, <ikalog.utils.matcher.IkaMatcher object at 0x10c7b68d0>), (846101, <ikalog.utils.matcher.IkaMatcher object at 0x10c7b68d0>), (846168, <ikalog.utils.matcher.IkaMatcher object at 0x10c7b68d0>), (846233, <ikalog.utils.matcher.IkaMatcher object at 0x10c7b68d0>), (846300, <ikalog.utils.matcher.IkaMatcher object at 0x10c7b68d0>), (846366, <ikalog.utils.matcher.IkaMatcher object at 0x10c7b68d0>), (846433, <ikalog.utils.matcher.IkaMatcher object at 0x10c7b68d0>), (846508, <ikalog.utils.matcher.IkaMatcher object at 0x10c7b68d0>), (846576, <ikalog.utils.matcher.IkaMatcher object at 0x10c7b68d0>), (846639, <ikalog.utils.matcher.IkaMatcher object at 0x10c7b68d0>), (846711, <ikalog.utils.matcher.IkaMatcher object at 0x10c7b68d0>), (846783, <ikalog.utils.matcher.IkaMatcher object at 0x10c7b68d0>), (846852, <ikalog.utils.matcher.IkaMatcher object at 0x10c7b68d0>), (846925, <ikalog.utils.matcher.IkaMatcher object at 0x10c7b68d0>), (846992, <ikalog.utils.matcher.IkaMatcher object at 0x10c7b68d0>), (847059, <ikalog.utils.matcher.IkaMatcher object at 0x10c7b68d0>), (847125, <ikalog.utils.matcher.IkaMatcher object at 0x10c7b68d0>), (847193, <ikalog.utils.matcher.IkaMatcher object at 0x10c7b68d0>), (847258, <ikalog.utils.matcher.IkaMatcher object at 0x10c7b68d0>), (847325, <ikalog.utils.matcher.IkaMatcher object at 0x10c7b68d0>), (847390, <ikalog.utils.matcher.IkaMatcher object at 0x10c7b68d0>), (847459, <ikalog.utils.matcher.IkaMatcher object at 0x10c7b68d0>), (847526, <ikalog.utils.matcher.IkaMatcher object at 0x10c7b68d0>), (847593, <ikalog.utils.matcher.IkaMatcher object at 0x10c7b68d0>), (847658, <ikalog.utils.matcher.IkaMatcher object at 0x10c7b68d0>), (847723, <ikalog.utils.matcher.IkaMatcher object at 0x10c7b68d0>), (847793, <ikalog.utils.matcher.IkaMatcher object at 0x10c7b68d0>), (847860, <ikalog.utils.matcher.IkaMatcher object at 0x10c7b68d0>), (847933, <ikalog.utils.matcher.IkaMatcher object at 0x10c7b68d0>), (848000, <ikalog.utils.matcher.IkaMatcher object at 0x10c7b68d0>), (848068, <ikalog.utils.matcher.IkaMatcher object at 0x10c7b68d0>), (848143, <ikalog.utils.matcher.IkaMatcher object at 0x10c7b68d0>), (848208, <ikalog.utils.matcher.IkaMatcher object at 0x10c7b68d0>), (848277, <ikalog.utils.matcher.IkaMatcher object at 0x10c7b68d0>), (848349, <ikalog.utils.matcher.IkaMatcher object at 0x10c7b68d0>), (848417, <ikalog.utils.matcher.IkaMatcher object at 0x10c7b68d0>), (848482, <ikalog.utils.matcher.IkaMatcher object at 0x10c7b68d0>), (848549, <ikalog.utils.matcher.IkaMatcher object at 0x10c7b68d0>), (848615, <ikalog.utils.matcher.IkaMatcher object at 0x10c7b68d0>), (848682, <ikalog.utils.matcher.IkaMatcher object at 0x10c7b68d0>), (848750, <ikalog.utils.matcher.IkaMatcher object at 0x10c7b68d0>), (848818, <ikalog.utils.matcher.IkaMatcher object at 0x10c7b68d0>), (848883, <ikalog.utils.matcher.IkaMatcher object at 0x10c7b68d0>), (848950, <ikalog.utils.matcher.IkaMatcher object at 0x10c7b68d0>), (849013, <ikalog.utils.matcher.IkaMatcher object at 0x10c7b68d0>), (849085, <ikalog.utils.matcher.IkaMatcher object at 0x10c7b68d0>), (849159, <ikalog.utils.matcher.IkaMatcher object at 0x10c7b68d0>), (849226, <ikalog.utils.matcher.IkaMatcher object at 0x10c7b68d0>), (849291, <ikalog.utils.matcher.IkaMatcher object at 0x10c7b68d0>), (849360, <ikalog.utils.matcher.IkaMatcher object at 0x10c7b68d0>), (849434, <ikalog.utils.matcher.IkaMatcher object at 0x10c7b68d0>), (849500, <ikalog.utils.matcher.IkaMatcher object at 0x10c7b68d0>), (849568, <ikalog.utils.matcher.IkaMatcher object at 0x10c7b68d0>), (849642, <ikalog.utils.matcher.IkaMatcher object at 0x10c7b68d0>), (849707, <ikalog.utils.matcher.IkaMatcher object at 0x10c7b68d0>), (849776, <ikalog.utils.matcher.IkaMatcher object at 0x10c7b68d0>), (849842, <ikalog.utils.matcher.IkaMatcher object at 0x10c7b68d0>), (849909, <ikalog.utils.matcher.IkaMatcher object at 0x10c7b68d0>)]
[(845958, <ikalog.utils.matcher.IkaMatcher object at 0x11215f0f0>), (846028, <ikalog.utils.matcher.IkaMatcher object at 0x11215f0f0>), (846101, <ikalog.utils.matcher.IkaMatcher object at 0x11215f0f0>), (846168, <ikalog.utils.matcher.IkaMatcher object at 0x11215f0f0>), (846233, <ikalog.utils.matcher.IkaMatcher object at 0x11215f0f0>), (846300, <ikalog.utils.matcher.IkaMatcher object at 0x11215f0f0>), (846366, <ikalog.utils.matcher.IkaMatcher object at 0x11215f0f0>), (846433, <ikalog.utils.matcher.IkaMatcher object at 0x11215f0f0>), (846508, <ikalog.utils.matcher.IkaMatcher object at 0x11215f0f0>), (846576, <ikalog.utils.matcher.IkaMatcher object at 0x11215f0f0>), (846639, <ikalog.utils.matcher.IkaMatcher object at 0x11215f0f0>), (846711, <ikalog.utils.matcher.IkaMatcher object at 0x11215f0f0>), (846783, <ikalog.utils.matcher.IkaMatcher object at 0x11215f0f0>), (846852, <ikalog.utils.matcher.IkaMatcher object at 0x11215f0f0>), (846925, <ikalog.utils.matcher.IkaMatcher object at 0x11215f0f0>), (846992, <ikalog.utils.matcher.IkaMatcher object at 0x11215f0f0>), (847059, <ikalog.utils.matcher.IkaMatcher object at 0x11215f0f0>), (847125, <ikalog.utils.matcher.IkaMatcher object at 0x11215f0f0>), (847193, <ikalog.utils.matcher.IkaMatcher object at 0x11215f0f0>), (847258, <ikalog.utils.matcher.IkaMatcher object at 0x11215f0f0>), (847325, <ikalog.utils.matcher.IkaMatcher object at 0x11215f0f0>), (847390, <ikalog.utils.matcher.IkaMatcher object at 0x11215f0f0>), (847459, <ikalog.utils.matcher.IkaMatcher object at 0x11215f0f0>), (847526, <ikalog.utils.matcher.IkaMatcher object at 0x11215f0f0>), (847593, <ikalog.utils.matcher.IkaMatcher object at 0x11215f0f0>), (847658, <ikalog.utils.matcher.IkaMatcher object at 0x11215f0f0>), (847723, <ikalog.utils.matcher.IkaMatcher object at 0x11215f0f0>), (847793, <ikalog.utils.matcher.IkaMatcher object at 0x11215f0f0>), (847860, <ikalog.utils.matcher.IkaMatcher object at 0x11215f0f0>), (847933, <ikalog.utils.matcher.IkaMatcher object at 0x11215f0f0>), (848000, <ikalog.utils.matcher.IkaMatcher object at 0x11215f0f0>), (848068, <ikalog.utils.matcher.IkaMatcher object at 0x11215f0f0>), (848143, <ikalog.utils.matcher.IkaMatcher object at 0x11215f0f0>), (848208, <ikalog.utils.matcher.IkaMatcher object at 0x11215f0f0>), (848277, <ikalog.utils.matcher.IkaMatcher object at 0x11215f0f0>), (848349, <ikalog.utils.matcher.IkaMatcher object at 0x11215f0f0>), (848417, <ikalog.utils.matcher.IkaMatcher object at 0x11215f0f0>), (848482, <ikalog.utils.matcher.IkaMatcher object at 0x11215f0f0>), (848549, <ikalog.utils.matcher.IkaMatcher object at 0x11215f0f0>), (848615, <ikalog.utils.matcher.IkaMatcher object at 0x11215f0f0>), (848682, <ikalog.utils.matcher.IkaMatcher object at 0x11215f0f0>), (848750, <ikalog.utils.matcher.IkaMatcher object at 0x11215f0f0>), (848818, <ikalog.utils.matcher.IkaMatcher object at 0x11215f0f0>), (848883, <ikalog.utils.matcher.IkaMatcher object at 0x11215f0f0>), (848950, <ikalog.utils.matcher.IkaMatcher object at 0x11215f0f0>), (849013, <ikalog.utils.matcher.IkaMatcher object at 0x11215f0f0>), (849085, <ikalog.utils.matcher.IkaMatcher object at 0x11215f0f0>), (849159, <ikalog.utils.matcher.IkaMatcher object at 0x11215f0f0>), (849226, <ikalog.utils.matcher.IkaMatcher object at 0x11215f0f0>), (849291, <ikalog.utils.matcher.IkaMatcher object at 0x11215f0f0>), (849360, <ikalog.utils.matcher.IkaMatcher object at 0x11215f0f0>), (849434, <ikalog.utils.matcher.IkaMatcher object at 0x11215f0f0>), (849500, <ikalog.utils.matcher.IkaMatcher object at 0x11215f0f0>), (849568, <ikalog.utils.matcher.IkaMatcher object at 0x11215f0f0>), (849642, <ikalog.utils.matcher.IkaMatcher object at 0x11215f0f0>), (849707, <ikalog.utils.matcher.IkaMatcher object at 0x11215f0f0>), (849776, <ikalog.utils.matcher.IkaMatcher object at 0x11215f0f0>), (849842, <ikalog.utils.matcher.IkaMatcher object at 0x11215f0f0>), (849909, <ikalog.utils.matcher.IkaMatcher object at 0x11215f0f0>)]
ゲームスタート。マップ モズク農園 ルール ガチエリア
[event] 14:10 on_game_start
<ikalog.scenes.game.start.GameStart object at 0x10c7b67b8>: switching to state _state_default
[event] 14:17 on_game_go_sign
プレイヤーをたおした！
[event] 14:31 on_game_killed
たおされた！
[event] 14:33 on_game_dead
<ikalog.scenes.game.dead.GameDead object at 0x11215f4a8>: switching to state _state_tracking
votes={'rapid_elite': 7, 'quickbomb': 1, 'h3reelgun_d': 1, 'splatscope': 1, 'barrelspinner': 1, 'megaphone': 1, 'liter3k_custom': 3, 'hokusai': 3, 'squiclean_a': 62, 'dynamo_tesla': 1, 'prime': 2}
last_death_reason {'sshooter_collabo': 2, 'megaphone': 1, 'pablo': 2, 'daioika': 2, 'nova': 1, 'carbon': 1, 'dualsweeper_custom': 1, '96gal_deco': 2, 'squiclean_a': 1, 'wakaba': 2, 'supershot': 2}
死因: squiclean_a
[event] 14:38 on_game_death_reason_identified  weapon = squiclean_a
<ikalog.scenes.game.dead.GameDead object at 0x11215f4a8>: switching to state _state_default
プレイヤーをたおした！
[event] 14:44 on_game_killed
たおされた！
[event] 14:49 on_game_dead
<ikalog.scenes.game.dead.GameDead object at 0x11215f4a8>: switching to state _state_tracking
votes={'hokusai': 1, 'dualsweeper': 1, 'pablo': 4, 'bucketslosher': 77, '52gal_deco': 1}
last_death_reason {'dualsweeper_custom': 1, 'nova': 1, '96gal_deco': 2, 'sshooter_collabo': 2, 'megaphone': 1, 'pablo': 2, 'daioika': 2, 'carbon': 1, 'bucketslosher': 1, 'squiclean_a': 1, 'wakaba': 2, 'supershot': 2}
死因: bucketslosher
[event] 14:54 on_game_death_reason_identified  weapon = bucketslosher
<ikalog.scenes.game.dead.GameDead object at 0x11215f4a8>: switching to state _state_default
プレイヤーをたおした！
[event] 15:02 on_game_killed
プレイヤーをたおした！
[event] 15:19 on_game_killed
たおされた！
[event] 15:22 on_game_dead
<ikalog.scenes.game.dead.GameDead object at 0x11215f4a8>: switching to state _state_tracking
votes={'tornado': 73, 'hissen': 5, 'h3reelgun': 2, 'pablo': 1, 'hokusai': 1, 'barrelspinner_deco': 1}
last_death_reason {'dualsweeper_custom': 1, 'tornado': 1, 'nova': 1, '96gal_deco': 2, 'sshooter_collabo': 2, 'megaphone': 1, 'pablo': 2, 'daioika': 2, 'carbon': 1, 'bucketslosher': 1, 'squiclean_a': 1, 'wakaba': 2, 'supershot': 2}
死因: tornado
[event] 15:28 on_game_death_reason_identified  weapon = tornado
<ikalog.scenes.game.dead.GameDead object at 0x11215f4a8>: switching to state _state_default
プレイヤーをたおした！
[event] 15:41 on_game_killed
たおされた！
[event] 15:44 on_game_dead
<ikalog.scenes.game.dead.GameDead object at 0x11215f4a8>: switching to state _state_tracking
votes={'splatroller': 12, 'quickbomb': 61, 'pablo': 4, 'bamboo14mk1': 1, 'hotblaster': 1, 'hokusai': 2, '96gal_deco': 2}
last_death_reason {'dualsweeper_custom': 1, 'tornado': 1, 'quickbomb': 1, 'nova': 1, '96gal_deco': 2, 'sshooter_collabo': 2, 'megaphone': 1, 'pablo': 2, 'daioika': 2, 'carbon': 1, 'bucketslosher': 1, 'squiclean_a': 1, 'wakaba': 2, 'supershot': 2}
死因: quickbomb
[event] 15:49 on_game_death_reason_identified  weapon = quickbomb
<ikalog.scenes.game.dead.GameDead object at 0x11215f4a8>: switching to state _state_default
プレイヤーをたおした！
[event] 16:09 on_game_killed
プレイヤーをたおした！
[event] 16:16 on_game_killed
プレイヤーをたおした！
[event] 16:34 on_game_killed
たおされた！
[event] 17:01 on_game_dead
<ikalog.scenes.game.dead.GameDead object at 0x11215f4a8>: switching to state _state_tracking
votes={'barrelspinner_deco': 3, 'hotblaster_custom': 40, 'sharp': 1, 'nova': 1, '96gal_deco': 1, 'sshooter_collabo': 2, 'pablo': 1, 'daioika': 1, 'octoshooter_replica': 1, 'hotblaster': 30, 'sharp_neo': 1, 'bucketslosher': 1}
last_death_reason {'dualsweeper_custom': 1, 'tornado': 1, 'hotblaster_custom': 1, 'quickbomb': 1, 'nova': 1, '96gal_deco': 2, 'sshooter_collabo': 2, 'megaphone': 1, 'pablo': 2, 'daioika': 2, 'carbon': 1, 'bucketslosher': 1, 'squiclean_a': 1, 'wakaba': 2, 'supershot': 2}
死因: hotblaster_custom
[event] 17:06 on_game_death_reason_identified  weapon = hotblaster_custom
<ikalog.scenes.game.dead.GameDead object at 0x11215f4a8>: switching to state _state_default
たおされた！
[event] 17:19 on_game_dead
<ikalog.scenes.game.dead.GameDead object at 0x11215f4a8>: switching to state _state_tracking
votes={'pablo': 18, 'barrelspinner': 66, '96gal_deco': 1}
last_death_reason {'dualsweeper_custom': 1, 'tornado': 1, 'hotblaster_custom': 1, 'barrelspinner': 1, 'quickbomb': 1, 'nova': 1, '96gal_deco': 2, 'sshooter_collabo': 2, 'megaphone': 1, 'pablo': 2, 'daioika': 2, 'carbon': 1, 'bucketslosher': 1, 'squiclean_a': 1, 'wakaba': 2, 'supershot': 2}
死因: barrelspinner
[event] 17:25 on_game_death_reason_identified  weapon = barrelspinner
<ikalog.scenes.game.dead.GameDead object at 0x11215f4a8>: switching to state _state_default
たおされた！
[event] 17:32 on_game_dead
<ikalog.scenes.game.dead.GameDead object at 0x11215f4a8>: switching to state _state_tracking
votes={'dualsweeper_custom': 1, 'barrelspinner_deco': 1, 'hotblaster_custom': 46, 'rapid_deco': 2, 'hokusai': 1, '96gal_deco': 3, 'sshooter_collabo': 1, 'pablo': 1, 'bamboo14mk1': 3, 'prime': 1, 'hotblaster': 20, 'sharp_neo': 1, 'bucketslosher': 2, 'prime_collabo': 1}
last_death_reason {'dualsweeper_custom': 1, 'tornado': 1, 'hotblaster_custom': 2, 'barrelspinner': 1, 'quickbomb': 1, 'nova': 1, '96gal_deco': 2, 'sshooter_collabo': 2, 'megaphone': 1, 'pablo': 2, 'daioika': 2, 'carbon': 1, 'bucketslosher': 1, 'squiclean_a': 1, 'wakaba': 2, 'supershot': 2}
死因: hotblaster_custom
[event] 17:37 on_game_death_reason_identified  weapon = hotblaster_custom
<ikalog.scenes.game.dead.GameDead object at 0x11215f4a8>: switching to state _state_default
プレイヤーをたおした！
[event] 17:44 on_game_killed
たおされた！
[event] 17:46 on_game_dead
<ikalog.scenes.game.dead.GameDead object at 0x11215f4a8>: switching to state _state_tracking
votes={'bucketslosher': 79, 'hokusai': 2, 'pablo': 1}
last_death_reason {'dualsweeper_custom': 1, 'tornado': 1, 'hotblaster_custom': 2, 'barrelspinner': 1, 'quickbomb': 1, 'nova': 1, '96gal_deco': 2, 'sshooter_collabo': 2, 'megaphone': 1, 'pablo': 2, 'daioika': 2, 'carbon': 1, 'bucketslosher': 2, 'squiclean_a': 1, 'wakaba': 2, 'supershot': 2}
死因: bucketslosher
[event] 17:51 on_game_death_reason_identified  weapon = bucketslosher
<ikalog.scenes.game.dead.GameDead object at 0x11215f4a8>: switching to state _state_default
プレイヤーをたおした！
[event] 18:09 on_game_killed
プレイヤーをたおした！
[event] 18:13 on_game_killed
たおされた！
[event] 18:19 on_game_dead
<ikalog.scenes.game.dead.GameDead object at 0x11215f4a8>: switching to state _state_tracking
votes={'nzap85': 1, 'h3reelgun_d': 2, 'tornado': 60, 'hissen': 9, 'h3reelgun': 3, 'hoko_barrier': 1, 'daioika': 4, 'dynamo': 1, 'trap': 1, '52gal': 1}
last_death_reason {'dualsweeper_custom': 1, 'tornado': 2, 'hotblaster_custom': 2, 'barrelspinner': 1, 'quickbomb': 1, 'nova': 1, '96gal_deco': 2, 'sshooter_collabo': 2, 'megaphone': 1, 'pablo': 2, 'daioika': 2, 'carbon': 1, 'bucketslosher': 2, 'squiclean_a': 1, 'wakaba': 2, 'supershot': 2}
死因: tornado
[event] 18:25 on_game_death_reason_identified  weapon = tornado
<ikalog.scenes.game.dead.GameDead object at 0x11215f4a8>: switching to state _state_default
たおされた！
[event] 18:38 on_game_dead
<ikalog.scenes.game.dead.GameDead object at 0x11215f4a8>: switching to state _state_tracking
votes={'liter3k': 2, 'pablo_hue': 1, 'barrelspinner_deco': 2, 'pablo': 15, 'daioika': 4, 'barrelspinner': 52, '52gal': 2, 'sharp_neo': 1, 'splatspinner': 1, 'tornado': 1, '96gal_deco': 2}
last_death_reason {'dualsweeper_custom': 1, 'tornado': 2, 'hotblaster_custom': 2, 'barrelspinner': 2, 'quickbomb': 1, 'nova': 1, '96gal_deco': 2, 'sshooter_collabo': 2, 'megaphone': 1, 'pablo': 2, 'daioika': 2, 'carbon': 1, 'bucketslosher': 2, 'squiclean_a': 1, 'wakaba': 2, 'supershot': 2}
死因: barrelspinner
[event] 18:43 on_game_death_reason_identified  weapon = barrelspinner
<ikalog.scenes.game.dead.GameDead object at 0x11215f4a8>: switching to state _state_default
たおされた！
[event] 18:51 on_game_dead
<ikalog.scenes.game.dead.GameDead object at 0x11215f4a8>: switching to state _state_tracking
votes={'splatcharger': 1, 'rapid_elite': 6, '52gal': 2, 'hissen': 1, 'splatroller_collabo': 1, 'pablo_hue': 4, 'hokusai': 2, 'sshooter_collabo': 1, 'quickbomb': 1, 'squiclean_b': 1, 'pablo': 4, 'liter3k': 1, 'squiclean_a': 60}
last_death_reason {'dualsweeper_custom': 1, 'tornado': 2, 'hotblaster_custom': 2, 'barrelspinner': 2, 'quickbomb': 1, 'nova': 1, '96gal_deco': 2, 'sshooter_collabo': 2, 'megaphone': 1, 'pablo': 2, 'daioika': 2, 'carbon': 1, 'bucketslosher': 2, 'squiclean_a': 2, 'wakaba': 2, 'supershot': 2}
死因: squiclean_a
[event] 18:56 on_game_death_reason_identified  weapon = squiclean_a
<ikalog.scenes.game.dead.GameDead object at 0x11215f4a8>: switching to state _state_default
<ikalog.outputs.statink.StatInk object at 0x10c79ed68>: Discarded screenshots
[event] 19:14 on_game_finish
trigger event
<ikalog.outputs.statink.StatInk object at 0x10c79ed68>: Gathered img_judge((720, 1280, 3))
[event] 19:21 on_result_judge  judge: lose, knockout: True
<ikalog.scenes.result_detail.ResultDetail object at 0x112163048>: switching to state _state_tracking
<ikalog.scenes.result_udemae.ResultUdemae object at 0x1121631d0>: switching to state _state_tracking
<ikalog.scenes.result_detail.ResultDetail object at 0x112163048>: switching to state _state_default
<ikalog.scenes.result_gears.ResultGears object at 0x112163400>: switching to state _state_tracking
<ikalog.scenes.result_udemae.ResultUdemae object at 0x1121631d0>:  udemae change: s 75 -> s 71
[event] 19:38 on_result_udemae  {'udemae_str': 's', 'udemae_exp': 75, 'udemae_str_after': 's', 'udemae_exp_after': 71}
<ikalog.scenes.result_udemae.ResultUdemae object at 0x1121631d0>: switching to state _state_default
  level: 50
  img_cash: (image)
  img_exp: (image)
  cash: 990304
  img_level: (image)
  exp:
  gear 0 : img_sub2
  gear 0 : img_main
  gear 0 : img_sub1
  gear 0 : img_name
  gear 0 : img_sub3
  gear 1 : img_sub2
  gear 1 : img_main
  gear 1 : img_sub1
  gear 1 : img_name
  gear 1 : img_sub3
  gear 2 : img_sub2
  gear 2 : img_main
  gear 2 : img_sub1
  gear 2 : img_name
  gear 2 : img_sub3
[event] 19:45 on_result_gears
<ikalog.scenes.result_gears.ResultGears object at 0x112163400>: switching to state _state_default
```

**Comment by vvakame** [comment]
環境
Mac OS X 10.10.5
Blackmagic UltraStudio Mini Recorder

自分で適当にデバッグログを入れて試してみてます。
IkaEngine.on_game_individual_result は呼ばれてない
StatInk.on_game_individual_result も呼ばれてない
StatInk.on_result_judge は呼ばれている

**Comment by vvakame** [comment]
IkaEngine.call_plugins でdebug=Trueにして python3 IkaLog.py &> log.txt を実行してロビー→ナワバリバトル1回→広場に戻って10秒放置 までのログです。

https://gist.github.com/vvakame/78adb2208e4c42a69e6e

**Comment by hasegaw** [comment]
静止画が認識できていない。
````
<ikalog.scenes.result_detail.ResultDetail object at 0x109aa32b0>: switching to state _state_tracking
img_diff_pixels 127 127 [127] False False
img_diff_pixels 120 120 [127, 120] False False
img_diff_pixels 120 137 [127, 120, 137] False False
img_diff_pixels 120 161 [127, 120, 137, 161] False False
img_diff_pixels 120 122 [120, 137, 161, 122] False False
img_diff_pixels 120 138 [137, 161, 122, 138] False False
img_diff_pixels 120 151 [161, 122, 138, 151] False False
img_diff_pixels 120 131 [122, 138, 151, 131] False False
img_diff_pixels 120 125 [138, 151, 131, 125] False False
img_diff_pixels 120 130 [151, 131, 125, 130] False False
img_diff_pixels 120 139 [131, 125, 130, 139] False False
img_diff_pixels 120 138 [125, 130, 139, 138] False False
img_diff_pixels 115 115 [130, 139, 138, 115] False False
img_diff_pixels 115 131 [139, 138, 115, 131] False False
img_diff_pixels 108 108 [138, 115, 131, 108] False False
img_diff_pixels 108 138 [115, 131, 108, 138] False False
img_diff_pixels 108 135 [131, 108, 138, 135] False False
img_diff_pixels 108 124 [108, 138, 135, 124] False False
img_diff_pixels 108 144 [138, 135, 124, 144] False False
img_diff_pixels 108 131 [135, 124, 144, 131] False False
img_diff_pixels 108 125 [124, 144, 131, 125] False False
img_diff_pixels 108 132 [144, 131, 125, 132] False False
img_diff_pixels 108 119 [131, 125, 132, 119] False False
img_diff_pixels 108 140 [125, 132, 119, 140] False False
img_diff_pixels 108 138 [132, 119, 140, 138] False False
img_diff_pixels 108 129 [119, 140, 138, 129] False False
img_diff_pixels 108 137 [140, 138, 129, 137] False False
img_diff_pixels 108 133 [138, 129, 137, 133] False False
img_diff_pixels 108 119 [129, 137, 133, 119] False False
img_diff_pixels 108 141 [137, 133, 119, 141] False False
img_diff_pixels 108 115 [133, 119, 141, 115] False False
img_diff_pixels 108 128 [119, 141, 115, 128] False False
img_diff_pixels 108 151 [141, 115, 128, 151] False False
img_diff_pixels 108 146 [115, 128, 151, 146] False False
img_diff_pixels 108 121 [128, 151, 146, 121] False False
img_diff_pixels 108 130 [151, 146, 121, 130] False False
img_diff_pixels 108 133 [146, 121, 130, 133] False False
img_diff_pixels 108 136 [121, 130, 133, 136] False False
img_diff_pixels 108 137 [130, 133, 136, 137] False False
img_diff_pixels 108 139 [133, 136, 137, 139] False False
img_diff_pixels 108 133 [136, 137, 139, 133] False False
img_diff_pixels 108 133 [137, 139, 133, 133] False False
img_diff_pixels 108 123 [139, 133, 133, 123] False False
img_diff_pixels 108 132 [133, 133, 123, 132] False False
img_diff_pixels 108 136 [133, 123, 132, 136] False False
img_diff_pixels 108 143 [123, 132, 136, 143] False False
img_diff_pixels 108 148 [132, 136, 143, 148] False False
<ikalog.scenes.result_gears.ResultGears object at 0x109aa36a0>: switching to state _state_tracking
<ikalog.scenes.result_detail.ResultDetail object at 0x109aa32b0>: 戦績画面を検出しましたが静止画を認識できませんでした。考えられる原因
  ・HDMIキャプチャデバイスからのノイズ入力が多い
　・ブロックノイズが多いビデオファイルを処理している
　・正しいフォーマットで画像が入力されていない
　min(diff_pixels): 108
````

・ diff_pixels のスレッショルドは 10
・ ひとつ元に戻すと 8 人目の認識に失敗することがある
・ その前に戻すと ikalog/engine.py と画面認識クラスとの分離する前のコード。それは避けたい
・静止画取得アルゴリズムを見直すかプラグインインタフェイス含めて修正しないと直らなそう

**Comment by hasegaw** [comment]
ちなみに DreCap HD1 を使った場合の min は 0
UltraStudio Mini Recorder だとどうして 100 越えたりするのか？中間色がきちんと取れてるということ？

**Comment by hasegaw** [comment]
97f1e68159d8cf53967753facc94f23781a4099d

**Comment by vvakame** [comment]
うまく動きました！ :+1:

**Comment by hasegaw** [comment]
f3ccc07

**Comment by vvakame** [comment]
うまく動きました！ :+1:

**Comment by hasegaw** [comment]
他のキャプチャデバイスで動作せず。

<ikalog.scenes.result_udemae.ResultUdemae object at 0x073E7DF0>: switching to st
ate _state_default
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\bin\Python34\lib\threading.py", line 920, in _bootstrap_inner
    self.run()
  File "C:\bin\Python34\lib\threading.py", line 868, in run
    self._target(*self._args, **self._kwargs)
  File "P:\IkaLog\IkaUI.py", line 191, in engine_thread_func
    engine.run()
  File "P:\IkaLog\ikalog\engine.py", line 212, in run
    self.process_frame()
  File "P:\IkaLog\ikalog\engine.py", line 180, in process_frame
    self.process_scene(scene)
  File "P:\IkaLog\ikalog\engine.py", line 144, in process_scene
    r = scene.match(context)
  File "P:\IkaLog\ikalog\scenes\scene.py", line 91, in match
    self._matched = self.match_no_cache(context)
  File "P:\IkaLog\ikalog\scenes\stateful_scene.py", line 36, in match_no_cache
    return self._state(context)
  File "P:\IkaLog\ikalog\scenes\result_detail.py", line 452, in _state_tracking
    '　min(diff_pixels): %s' % min(self._diff_pixels),
ValueError: min() arg is an empty sequence
